### ISSUE TITLE
Update Node.js package to current version with JSON-style .csslintrc

### ISSUE THREAD

**Issue by BOOMER74** [CSSLint/csslint#540] opened 2014-09-10 18:57 UTC
Need to update version in NPM to current with support JSON-style .csslintrc

**Comment by seanconaty** [comment] 2015-02-06 01:33
:+1: for this!

**Comment by Arcanemagus** [comment] 2016-06-07 16:17
Duplicate of #514.

**Comment by Arcanemagus** [comment] 2016-07-15 16:05
@XhmikosR this should be closed now that v1.0.0 is out.

**Closed** 2016-07-15 16:52 UTC
Labels: Duplicate
