### ISSUE TITLE
Why is CssLint not updated on NPM since almost 3 years?

### ISSUE THREAD

**Issue by patlecat** [CSSLint/csslint#659] opened 2016-06-07 12:40 UTC
It seems the development never stopped but why then not update the npm-extension?

And how can I create an npm-extension from the master myself and install it through npm?

**Comment by Arcanemagus** [comment] 2016-06-07 16:17
Duplicate of #514.

You can simply create your own `npm` package with a different name with the current contents of `master` btw.

**Closed** 2016-07-03 22:08 UTC
