### ISSUE TITLE
What about tagging a new release?

### ISSUE THREAD

**Issue by robertfausk** [CSSLint/csslint#592] opened 2015-04-28 07:52 UTC
There are very many new commits since last release in August 2013.

**Comment by lorenz068** [comment] 2015-04-29 00:16
True that!

**Comment by jawshooah** [comment] 2015-04-29 00:26
Or perhaps put out a request for more collaborators? I realize that @nschonni and @stubbornella probably have a lot on their plates, so adding a collaborator or two to the repo would be a huge help in keeping things updated.

**Comment by cvrebert** [comment] 2015-05-24 19:14
Duplicate of #514.

**Comment by frvge** [comment] 2016-02-11 22:56
Closing because of duplicate. We will see about a new release soon. CC: @XhmikosR

**Closed by frvge** 2016-02-11 22:56 UTC

**Comment by XhmikosR** [comment] 2016-02-12 08:43
@frvge: I don't have npm push rights, so we'll need @stubbornella or @nschonni to do this for us.
